
test:
  adapter: postgresql
  encoding: unicode
  database: mirojune_test
  pool: 5
  username: 
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: skteevents_production
  pool: 5
  username: 
  password: 


